=== Running VeggieVault Application as a JAR file

.Prerequisites
Before you can run the VeggieVault application, make sure you have the following software installed:

1. Java 17
2. Docker
3. Maven

.Running PostgreSQL on Docker
The VeggieVault application requires a PostgreSQL database to run. To simplify the process of setting up a database, we'll run PostgreSQL on a Docker container.

- Open a terminal and navigate to the directory containing the docker readme file.
- Go thorough the steps in the src/main/docker/readme.adocs
- You should see a container named pgdb in the list of running containers.

.Building and Running the VeggieVault Application
- Open a terminal and navigate to the root directory of the VeggieVault application.
- Run the following command to build the application:
----
mvn clean package
----
- This will create a JAR file named veggievault-1.0-SNAPSHOT.jar in the target directory.
- Run the following command to start the application:
----
java -jar target/veggievault-1.0-SNAPSHOT.jar
----
This will start the application on port 8088.

- Open a web browser and go to http://localhost:8088 to access the application.

.Running Jenkins on Localhost:8090
- Note: Jenkins is installed in docker so open terminal and run the command: +
---
$ docker start jenkins
---
- Open a web browser and go to http://localhost:8090.
- Follow the prompts to set up Jenkins.

That's it! You should now be able to use the VeggieVault application and Jenkins on your local machine.