server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/harvestdb?currentSchema=veggieshop
    username: dmainali
    password: Welcome1

logging:
  level:
    ROOT: warn
    com.dirghayu.myshop: info
